name: Elixir CI

on:
  push:
    branches:
      - develop
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      SCIXIR_MINIO_REDIS_URL: redis://redis.localhost:6379/0
      SCIXIR_MINIO_BROADWAY_LIST_NAME: minio_events
      SCIXIR_SCISSOR_BROADWAY_LIST_NAME: scissor_events
      SCIXIR_VERSIONS: eyJwcm9qZWN0X2F0dGFjaG1lbnQiOnsidGh1bWJuYWlsIjp7ImdyYXZpdHkiOiJjZW50ZXIiLCJyZXNpemUiOnsiaGVpZ2h0Ijo5NiwidHlwZSI6ImZpbGwiLCJ3aWR0aCI6MTI4fSwic3RyaXAiOnRydWV9fSwicHJvamVjdF9jb3Zlcl9pbWFnZSI6eyJkZWZhdWx0Ijp7ImdyYXZpdHkiOiJjZW50ZXIiLCJyZXNpemUiOnsiaGVpZ2h0IjoxNjUsInR5cGUiOiJmaWxsIiwid2lkdGgiOjI2NX0sInN0cmlwIjp0cnVlfX19
      SCIXIR_SCISSOR_PROCESSOR_STAGES: 10
      SCIXIR_MINIO_ACCESS_KEY:  minio
      SCIXIR_MINIO_SECRET_KEY: minio123
      SCIXIR_MINIO_SCHEME: http://
      SCIXIR_MINIO_HOST: minio
      SCIXIR_MINIO_PORT: 9090

    steps:
    - uses: actions/setup-elixir@v1.0.0
      with:
        otp-version: 22.x
        elixir-version: 1.9.x

    - uses: actions/checkout@v1

    - name: Install Dependencies
      run: |
        cp config/dev.example.exs config/dev.exs
        mix local.rebar --force
        mix local.hex --force
        mix deps.get

    - name: Run Formatter
      run: mix format --check-formatted
